### ISSUE TITLE
Question: Why is custom resources Keycloak not namespaced?

### ISSUE THREAD

**Issue by webwurst** [kiwigrid/keycloak-client-controller#10]
I would like to create a Keycloak instance in a certain namespace. I am also fine having this instance and the controller in the same namespace. In that case I also wouldn't need the serviceaccount and rolebindings, I think.

`$ kubectl api-resources --api-group k8s.kiwigrid.com`
```
NAME              SHORTNAMES   APIGROUP           NAMESPACED   KIND
keycloakclients   kcc          k8s.kiwigrid.com   true         KeycloakClient
keycloakrealms    kcr          k8s.kiwigrid.com   false        KeycloakRealm
keycloaks         kc           k8s.kiwigrid.com   false        Keycloak
```

Is there a special reasoning to not have these resources namespaced?

**Comment by axdotl** [comment]
Hi and sorry for late response (were on vacation).

We decided to handle namespaces and instances as global, to avoid redundant definitions in multiple namespaces - this is mainly driven by our deployment scenario where we using clusters to separate stages and k8s namespaces to separate teams. On the other hand clients are always related to an application which are deployed to a specific namespace.

Hope this helps.

**Comment by rpahli** [comment]
keycloaks and keycloakrealms are scoped to a keycloak not to a namespace, if we provide a keycloak reference it is always the same keycloak as well as the same realm so we wont duplicate this resources across our namespaces
