### ISSUE TITLE
API

### ISSUE THREAD

**Issue by kfox1111** [kiwigrid/keycloak-client-controller#22]
I'm trying to convince the Keycloak Operator developers to support pointing at an external Keycloak so their management CRD's can be used the same way as they keycloak-controller. If they can not be convinced, could the keycloak-controller support the use of the keycloak-operator's management CRD's so that users don't have to switch between API's moving between the keycloak-operator and keycloak-controller?

**Comment by kfox1111** [comment]
https://issues.redhat.com/browse/KEYCLOAK-12662

**Comment by monotek** [comment]
I think this is out of scope for us too.
