### ISSUE TITLE
Manage keycloak instances deployed via helm?

### ISSUE THREAD

**Issue by Coleslaw3557** [kiwigrid/keycloak-client-controller#32]
Hey there,

So I've been trying to determine if this is supported or not.

Can I use Keycloak-Controller to manage Keycloak instances deployed to K8S in other ways? 
For example, I've deployed Keycloak via the codecentric helm chart. 
https://github.com/codecentric/helm-charts/tree/master/charts/keycloak

Thank you kindly for any pointers...

**Comment by rpahli** [comment]
The controller manages only resources inside a keycloak so it doesn't matter how the keykloak is deployed. We deploy our keycloaks with helm.

**Comment by Coleslaw3557** [comment]
Ah! It just clicked. I thought the first example was some strange way to deploy a keycloak instance but is in fact just telling the controller how to connect to my existing instance. Thank you!
