### ISSUE TITLE
Document the process to start the controller

### ISSUE THREAD

**Issue by LoicGombeaud** [kiwigrid/keycloak-client-controller#7]
Hallöchen!

First of all thanks a lot for creating and open-sourcing the controller and the associated CRDs. It will greatly assist us in the creation and destruction of ephemeral environments in our CI/CD set-up.

I'm having trouble deploying the controller on my cluster: I managed to build the Docker image by replicating the `mvn` commands from Travis CI, but when I run it I get the following error:
```
16:05:15.952 1-thread-1 WARN  io.fabric8.kubernetes.client.Config Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
```

I suppose a service account token needs to be mounted as a secret in the container, could you please help me figure out which permissions this service account should have, what its name should be, etc.?

Any pointer would be very much appreciated!

Danke im Voraus,
Loïc

**Comment by axdotl** [comment]
Maybe the related Helm Chart can you provide more insights: https://github.com/kiwigrid/helm-charts/tree/master/charts/keycloak-controller

If you still have trouble get the controller up and running, let us know.

**Comment by LoicGombeaud** [comment]
That's the info I was missing - thanks. I created a PR to add a link to the chart, in case anyone else is in the same situation: https://github.com/kiwigrid/keycloak-controller/pull/8

**Comment by monotek** [comment]
thanks! 
merged :-)
